version: '3.9'
services:
  web:
    build: .
    ports:
      - "8011:8011"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=fast_todo_app
      - POSTGRES_PORT=5432
    volumes:
      - ./app:/app/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-net
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --reload --port 8011"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=fast_todo_app
    ports:
      - "5432:5432"
    networks:
      - my-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d fast_todo_app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  my-net:
    driver: bridge
