api:
  insecure: true
  dashboard: true

providers:
  swarm:
    network: my-net
    exposedbydefault: false

# accessLog: {}

log:
  level: DEBUG

entryPoints:
  web:
    address: :80

  websecure:
    address: :443
